export const menu = [
  {
    id: 1,
    course: "Starter",
    dish: "Chilli Chicken Bites",
    price: 6.95,
    basket: 0,
    total: 0,
  },
  {
    id: 2,
    course: "Starter",
    dish: "Garlic Mushrooms",
    price: 4.95,
    basket: 0,
    total: 0,
  },
  {
    id: 3,
    course: "Starter",
    dish: "Cheese Bites",
    price: 6.95,
    basket: 0,
    total: 0,
  },
  {
    id: 4,
    course: "Starter",
    dish: "Garlic Bread",
    price: 2.95,
    basket: 0,
    total: 0,
  },
  {
    id: 5,
    course: "Main",
    dish: "Meatball Mariana",
    price: 12.95,
    basket: 0,
    total: 0,
  },
  {
    id: 6,
    course: "Main",
    dish: "Swordfish Sicillian",
    price: 14.95,
    basket: 0,
    total: 0,
  },
  {
    id: 7,
    course: "Main",
    dish: "Grilled Swordfish",
    price: 15.95,
    basket: 0,
    total: 0,
  },
  {
    id: 8,
    course: "Main",
    dish: "Chicken Cacciatore",
    price: 12.95,
    basket: 0,
    total: 0,
  },
  {
    id: 9,
    course: "Dessert",
    dish: "Tiramisu",
    price: 4.95,
    basket: 0,
    total: 0,
  },
  {
    id: 10,
    course: "Dessert",
    dish: "Panettone",
    price: 4.95,
    basket: 0,
    total: 0,
  },
  {
    id: 11,
    course: "Dessert",
    dish: "Maritozzo",
    price: 4.95,
    basket: 0,
    total: 0,
  },
  {
    id: 12,
    course: "Dessert",
    dish: "Babà Napoletano",
    price: 5.95,
    basket: 0,
    total: 0,
  },
];
